### ISSUE TITLE
Support for overlays

### ISSUE THREAD

**Issue by ericdallo** [tecosaur/screenshot#2]
Very cool project indeed!

It'd be great if this could support emacs overlays:

Raw picture (0 references)
![image](https://user-images.githubusercontent.com/7820865/103490384-29009980-4dfa-11eb-815c-86fac89369b4.png)

screenshot.el
![test](https://user-images.githubusercontent.com/7820865/103490380-2140f500-4dfa-11eb-83e0-f607f0ce79c3.png)

Also, is there any option for width size? it cropped the `:require` form.

**Comment by tecosaur** [comment]
To capture overlays, try setting this:
![image](https://user-images.githubusercontent.com/20903656/103499556-7a08a000-4e83-11eb-905f-27d39c160f64.png)
This will use a narrowed clone of the current buffer, instead of a copy of the text.

I'd also recommend increasing this minimum width:
![image](https://user-images.githubusercontent.com/20903656/103499578-8ee53380-4e83-11eb-9188-2f27f45f29b0.png)
I'm not sure why increasing the min-width helps, but frankly, that's an upstream issue.

**Comment by tecosaur** [comment]
@ericdallo did this work for you?

**Comment by ericdallo** [comment]
I didn't try yet :/ I'm waiting for this arrive on MELPA, would you mind that?

**Comment by tecosaur** [comment]
Still waiting? :sweat_smile:

**Comment by ericdallo** [comment]
Is this available on melpa, I couldn't find it?

**Comment by tecosaur** [comment]
Still no, but I've finally fixed the byte-compile issue that was blocking it.

**Comment by tecosaur** [comment]
Well, this does work, so I'm going to go ahead and close the issue.
